title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links: 
  - name:         Blog
    url:          http://muan.co
  - name:         Email
    url:          mailto:hello@muan.co
  - name:         GitHub
    url:          http://github.com/muan

auto:             true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]